apiVersion: cert-manager.io/v1

kind: Certificate

metadata: 
  name: nginx-tls-cordeiro

spec:
  commonName: nginx.cordeiro.iff.edu.br
  secretName: cer-nginx-cordeiro
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  
  dnsNames:
    - nginx.cordeiro.iff.edu.br
